FROM gradle:8.0.2-jdk17 AS TEMP_BUILD_IMAGE
ARG CLIENT_ID
ARG CLIENT_SECRET

ARG DATABASE_DB
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_HOST

ENV APP_HOME=/usr/app/

ENV CLIENT_ID $CLIENT_ID
ENV CLIENT_SECRET $CLIENT_SECRET

ENV DATABASE_DB $DATABASE_DB
ENV DATABASE_USERNAME $DATABASE_USERNAME
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV DATABASE_HOST $DATABASE_HOST

WORKDIR $APP_HOME
COPY build.gradle settings.gradle $APP_HOME
COPY gradle $APP_HOME/gradle
COPY --chown=gradle:gradle src $APP_HOME/src
COPY --chown=gradle:gradle config $APP_HOME/config

RUN gradle clean build

# actual container
FROM amazoncorretto:17
ENV ARTIFACT_NAME=splitter-0.0.1-SNAPSHOT.jar
ENV APP_HOME=/usr/app/

ARG CLIENT_ID
ARG CLIENT_SECRET

ARG DATABASE_DB
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_HOST

ENV CLIENT_ID $CLIENT_ID
ENV CLIENT_SECRET $CLIENT_SECRET

ENV DATABASE_DB $DATABASE_DB
ENV DATABASE_USERNAME $DATABASE_USERNAME
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV DATABASE_HOST $DATABASE_HOST

WORKDIR $APP_HOME
COPY --from=TEMP_BUILD_IMAGE $APP_HOME/build/libs/$ARTIFACT_NAME .

EXPOSE 9000
ENTRYPOINT exec java -jar ${ARTIFACT_NAME}