spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
  datasource:
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: jdbc:postgresql://localhost:5432/${DATABASE_DB}
server:
  port: 9000
